version: "3"

services: 
    
    frontend:
        build: desafio-frontend
        container_name: imersao-fullcycle-3-desafio-frontend-app
        entrypoint: ./.docker/entrypoint.sh
        ports: 
            - "3001:3000"
        volumes: 
            - ./desafio-frontend:/frontend/home/node/app
        extra_hosts: 
            - "host.docker.internal:172.17.0.1"
    
    backend:
        build: desafio-backend
        container_name: imersao-fullcycle-3-desafio-backend-app
        entrypoint: ./.docker/entrypoint.sh
        ports: 
            - "3000:3000"
        volumes: 
            - ./desafio-backend:/backend/home/node/app
        extra_hosts: 
            - "host.docker.internal:172.17.0.1"
        depends_on: 
            - frontend
